# Generated by Django 2.2 on 2020-01-31 17:30

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datastructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastructure',
            name='body',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
