# Generated by Django 2.2 on 2020-02-13 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datatypes', '0001_initial'),
        ('datastructure', '0002_datastructure_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataTypeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('datastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastructure.Datastructure')),
                ('datatType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datatypes.Datatype')),
            ],
            options={
                'unique_together': {('datastructure', 'datatType')},
            },
        ),
    ]
