# Generated by Django 2.2 on 2020-02-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datatypes', '0001_initial'),
        ('datastructure', '0004_remove_datastructure_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatypemapping',
            old_name='datatType',
            new_name='datatype',
        ),
        migrations.AlterUniqueTogether(
            name='datatypemapping',
            unique_together={('datastructure', 'datatype')},
        ),
    ]
