# Generated by Django 2.2 on 2020-02-13 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastructure', '0005_auto_20200213_2026'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datatypemapping',
            unique_together=set(),
        ),
    ]
