# Generated by Django 2.2 on 2020-02-14 14:14

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datastructure', '0006_auto_20200213_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatastructureData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('datastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastructure.Datastructure')),
            ],
        ),
    ]
